name: xdlake

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    uses: ./.github/workflows/lib/test.yml
